wrapperVersion=3.3.4
distributionType=only-script
<<<<<<< HEAD
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.16/apache-maven-3.9.16-bin.zip
=======
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.14/apache-maven-3.9.14-bin.zip
>>>>>>> a1521e11f6d3a3e6ee6ff6ed7a759c108d2c2e10
