
server.port=9060
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=JDBC:mysql://${MYSQL_HOST:localhost}:3306/db_tradex
spring.datasource.username=root
spring.datasource.password=@9060
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.application.name=Trading

