spring.application.name=Trading

server.port=1305
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_tradex
spring.datasource.username=root
spring.datasource.password=@9060
spring.datasource.driver-class-name=con.mysql.cj.jdbc.Driver